version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=Asia/Jerusalem
    restart: unless-stopped
    privileged: true
    network_mode: host
    command: /bin/bash -c "apk add --no-cache git openssh && /init"

  matter-server:
      container_name: matter-server
      image: ghcr.io/home-assistant-libs/python-matter-server:stable
      restart: unless-stopped
      network_mode: host
      volumes:
        - ./matter-server-data:/data
      # Required for Bluetooth/Thread commissioning:
      security_opt:
        - apparmor=unconfined